### PR TITLE
feat: add typescript declaration file

### LINKED ISSUE #109: TypeScript support？

### PR DESCRIPTION
**Pull request by navono**
Typescript support

Close #109

### CODE REVIEW

**Comment by asbish** [comment]
Good patch!
But I think that FluentSender.emit() method needs more argument types.
What do you think to try using Generics and Overloads like below?
```javascript
type Timestamp = number | Date;
type Callback = (err?: Error) => void;

class FluentSender<T> {
    constructor(tagPrefix: string, options: Options);
    emit(data: T, callback?: Callback): void;
    emit(data: T, timestamp: Timestamp, callback?: Callback): void;
    emit(label: string, data: T, callback?: Callback): void;
    emit(label: string, data: T, timestamp: Timestamp, callback?: Callback): void;
    end(label: string, data: T, callback: Callback): void;
}

// And haven't you forget emit() function?
function emit<T>(...) {...}
```

**Comment by navono** [comment]
>type Timestamp = number | Date;
type Callback = (err?: Error) => void;
>
>class FluentSender<T> {
    constructor(tagPrefix: string, options: Options);
    emit(data: T, callback?: Callback): void;
    emit(data: T, timestamp: Timestamp, callback?: Callback): void;
    emit(label: string, data: T, callback?: Callback): void;
    emit(label: string, data: T, timestamp: Timestamp, callback?: Callback): void;
    end(label: string, data: T, callback: Callback): void;
} 

yeah, you are right. I didn't noticed it when I wrote `FluentSender`. Generics and Overloads is OK, I will fix it.

>// And haven't you forget emit() function?
function emit<T>(...) {...}

you mean in the `fluentLogger` namespace? I didn't figure it out too well.

**Comment by okkez** [comment]
Thanks!

**Comment by okkez** [comment]
Released v3.1.0

**Pull request merged**
