### PR TITLE
Support EventTime

### LINKED ISSUE #59: fluentd update to v0.14 EventTime
can you support EvenTime in fluent-logger-node

### PR DESCRIPTION
**Pull request by okkez**
Close #59

### CODE REVIEW

**Comment by linxuanwei** [comment]
is it convenient for you to merge this to master？

**Comment by okkez** [comment]
@linxuanwei Could you try this branch?

**Comment by linxuanwei** [comment]
@okkez  
Sure, I will try/test your branch and give feedback as soon as possible.
Thank u very much.

**Comment by linxuanwei** [comment]
Hi， @okkez  

My team has both tested 'support-connect-event' and 'support-event-time' branches.

All passed the test.

I think there is no problem with these two branches.

Please merge to master, thank you very much!

**Comment by okkez** [comment]
@linxuanwei Thank you for testing!

**Pull request merged**
