### PR TITLE
#135 Error handling and flushing message on reconnection.

### PR DESCRIPTION
**Pull request by sphansekar-cci**
#135 Fixed.

### CODE REVIEW

**Comment by sphansekar-cci** [comment]
@okkez Please review the changes and let me know if there are anything more to be done.

**Comment by okkez** [comment]
@sphansekar-cci Please check DCO result.

**Comment by sphansekar-cci** [comment]
@okkez It's done.

**Comment by okkez** [comment]
Thanks!

**Comment by sphansekar-cci** [comment]
When can I expect for the new version to be released?

**Comment by okkez** [comment]
Maybe after #132 will be resolved.

**Pull request merged**
