### PR TITLE
Add Node 4.0 support

### PR DESCRIPTION
**Pull request by aheckmann**
Adds support for:
- NodeJS 4.0.x
- iojs 1x
- iojs 2x
- iojs 3x

Now uses [msgpack5](https://github.com/mcollina/msgpack5), the recommended NodeJS module on the [official msgpack website](http://msgpack.org/).

see #28

### CODE REVIEW

**Comment by repeatedly** [comment]
Could you squash commits into one? `temp;` commit are no information ;|

**Comment by aheckmann** [comment]
ugh sorry. incoming

**Comment by aheckmann** [comment]
done

**Comment by repeatedly** [comment]
Thanks!

**Comment by aheckmann** [comment]
would be great to get a release on npm.

**Pull request merged**
