### PR TITLE
test for node 0.10 and 0.12

### PR DESCRIPTION
**Pull request by Eiryyy**

### CODE REVIEW

**Comment by repeatedly** [comment]
node.js v0.6 or v0.8 is still active?
Can we remove these version from travis setting?

**Comment by okkez** [comment]
@repeatedly  Node.js v0.6 and v0.8 have been reached EOL.
So, we can remove them.

**Comment by okkez** [comment]
I arranged .travis.yml.

See also #25

**Comment by repeatedly** [comment]
Thanks for the PR! I merged new PR based on this patch.
So closed.

**Pull request closed without merging**
